//
//  GameInteractor.swift
//  iOSweep
//
//  Created by Ryan Ayers on 9/6/20.
//  Copyright (c) 2020 Ryan Ayers. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GameBusinessLogic
{
  func doSomething(request: Game.Something.Request)
}

protocol GameDataStore
{
  //var name: String { get set }
}

class GameInteractor: GameBusinessLogic, GameDataStore
{
  var presenter: GamePresentationLogic?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Game.Something.Request)
  {
    let response = Game.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
